name: Github_Action_Basics

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: First step
      run: echo Hello World from test

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Second step
      run: |
        echo first line
        echo second line
